# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('price', models.FloatField()),
                ('img_url', models.URLField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('lenght', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('ref', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VendorWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('url', models.URLField()),
                ('url_search', models.CharField(max_length=255)),
                ('re_articles_number', models.CharField(max_length=255)),
                ('re_article_link', models.CharField(max_length=255)),
                ('articles_per_page', models.IntegerField()),
                ('re_name', models.CharField(max_length=255)),
                ('re_price', models.CharField(max_length=255)),
                ('re_img', models.CharField(max_length=255)),
                ('re_width', models.CharField(max_length=255)),
                ('re_height', models.CharField(max_length=255)),
                ('re_lenght', models.CharField(max_length=255)),
                ('re_color', models.CharField(max_length=255)),
                ('re_ref', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.VendorWebsite'),
        ),
    ]
